name: Test and publish library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 17.x]

    steps:
    - uses: actions/checkout@v2

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.10.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Setup Python
      uses: actions/setup-python@v3.0.0
    - name: Install susc
      run: pip install susc

    - run: pnpm i
    - run: pnpm test

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/clover.xml
        flags: unittests

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.10.0
    - uses: actions/setup-node@v2
      with:
        cache: 'pnpm'

    - run: pnpm i
    - run: pnpm build

    - name: write npmrc
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - run: pnpm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

